### ISSUE TITLE
Struct tags should be something different than `json`

### ISSUE THREAD

**Issue by mikroskeem** [philandstuff/dhall-golang#10]
`dhall` perhaps?

**Comment by philandstuff** [comment]
I haven't documented why I went with `json` so here's an explanation: my thinking is that a lot of code is already instrumented for use with `json` tags, and it'd be great to piggyback on that work that's already there.  Dhall only needs a subset of the features of `json` tags so we might as well reuse them rather than creating a new one.

This approach is used in other libraries such as [codec](https://godoc.org/github.com/ugorji/go/codec) which support `json` tags.

I don't currently see a need for separate `dhall` tags, other than to reduce confusion.  Even then, I'd still like to support `json` tags as well if possible.

**Comment by mikroskeem** [comment]
That gets bit annoying when I want to read from dhall with one variable names and serialize using same struct but have different variable names. I can do that fine with [toml](https://github.com/BurntSushi/toml) right now by specifying different tag names.

**Comment by philandstuff** [comment]
I’m not sure I follow - can you give an example to help me understand? When
you say “serialize”, do you mean serialize to JSON? (I’m guessing yes but I
want to be sure.)

Is this a specific use case you have or is it a hypothetical?

**Comment by mikroskeem** [comment]
> do you mean serialize to JSON

In this context, yes.

> Is this a specific use case you have

Yes.

> can you give an example

For example, with TOML I do the following:

```golang
var a struct {
    MyThing string `toml:"my_thing",json:"myThing"`
}
```

I intend to replace TOML with Dhall soon, but that pretty much means duplicating structures or finding an alternative way for renaming fields for json.

**Comment by philandstuff** [comment]
Thank you, this seems like a clear use case.  The example helps me to understand why it's a problem and how much pain it causes.

Based on this feedback, I intend to switch from `json` to `dhall` and for now drop the capability to read `json` tags.  I can always add it again if people need it later, but for now I'd rather keep dhall-golang small and focussed and not have too many extraneous features.

**Comment by erikkaplun** [comment]
just a small note, but maybe also update the README accordingly?

**Comment by philandstuff** [comment]
@erikkaplun update it how? It wasn't using the `json` tags so there's nothing to change? :man_shrugging:

**Comment by erikkaplun** [comment]
so no tags at all also works?

**Comment by philandstuff** [comment]
Yes, if you don’t use a tag the field name will be used instead.

**Comment by jgillich** [comment]
> my thinking is that a lot of code is already instrumented for use with json tags, and it'd be great to piggyback on that work that's already there.

*sad trombone*

Could we fall back on `json` tags if no `dhall` tag exists? I want to use Dhall with Kubernetes resources and objects such as `ObjectMeta` and `TypeMeta` only have json tags. Uppercasing looks out of place and also deviates a lot from the json representation that people are used to.

**Comment by jgillich** [comment]
@philandstuff https://github.com/jgillich/dhall-golang/commit/c252a2668138ef1a61f05281d38ef64c5c06f40a
I'll have to test this for a bit but is this something you'd merge?
