### ISSUE TITLE
Test failure on windows

### ISSUE THREAD

**Issue by msingle** [philandstuff/dhall-golang#42]
Test output:

```
+ Failure [0.001 seconds]
Import resolution
C:/Users/mts001/source/repos/misc/dhall-golang/imports/imports_test.go:29
  local imports
  C:/Users/mts001/source/repos/misc/dhall-golang/imports/imports_test.go:181
    Resolves as Text [It]
    C:/Users/mts001/source/repos/misc/dhall-golang/imports/imports_test.go:182

    Expected
        <term.TextLit>: {
            Chunks: nil,
            Suffix: "here is some text\r\n",
        }
    to equal
        <term.TextLit>: {
            Chunks: nil,
            Suffix: "here is some text\n",
        }

    C:/Users/mts001/source/repos/misc/dhall-golang/imports/imports_test.go:186
```

Hooray for windows line endings!

It looks like this is due to `imports/testdata/just_text.txt` 
Go should be fairly agnostic about reading line endings and after looking (very briefly) at the dhall spec it looks like it will accept windows line endings as well.

dhall.peg seems to have `EOL ← "\n" / "\r\n" { return []byte{'\n'}, nil }`, which might be part of this. 

I don't have any  .gitattributes doing anything about line endings.

**Comment by philandstuff** [comment]
Thanks for the bug report!  I've raised #43 to try to fix it but I don't have access to a Windows machine to test.  Would you mind checking out that branch and testing?

**Comment by msingle** [comment]
@philandstuff it doesn't seem to have done it. I'm getting the same error.

**Comment by philandstuff** [comment]
Ok, how about #45? It's a hack but it should hopefully work?

I'm open to suggestions for a fix too :)

**Comment by philandstuff** [comment]
I'm going to close this soon if I don't hear anything more, since I don't have a windows machine to do my own testing.  I would still accept contributions that fix windows, but I'm not going to keep this issue open if it's not making progress.
