### ISSUE TITLE
Unmarshaling into struct pointer does not work

### ISSUE THREAD

**Issue by mikroskeem** [philandstuff/dhall-golang#9]
Consider following example:
```go
var config struct {
    Foo bool `json:"foo"`
    Bar *struct {
        Baz string `json:"baz"`
    } `json:"bar"`
}
```

Unmarshalling into the config throws an error:
```
panic: Don't know how to decode map[(redacted)] into ptr

goroutine 1 [running]:
github.com/philandstuff/dhall-golang.decode(0x16ad260, 0xc0003d28d0, 0x14ec8a0, 0x1a88fc0, 0x196)
	/Users/mark/go/pkg/mod/github.com/philandstuff/dhall-golang@v1.0.0-rc.2/unmarshal.go:237 +0xfa0
github.com/philandstuff/dhall-golang.decode(0x16ad260, 0xc0003d27e0, 0x15763c0, 0x1a88fc0, 0x199)
	/Users/mark/go/pkg/mod/github.com/philandstuff/dhall-golang@v1.0.0-rc.2/unmarshal.go:198 +0x583
github.com/philandstuff/dhall-golang.Decode(0x16ad260, 0xc0003d27e0, 0x14ec8e0, 0x1a88fc0)
	/Users/mark/go/pkg/mod/github.com/philandstuff/dhall-golang@v1.0.0-rc.2/unmarshal.go:46 +0xd4
github.com/philandstuff/dhall-golang.Unmarshal(0xc0000c4480, 0x207, 0x407, 0x14ec8e0, 0x1a88fc0, 0x0, 0x0)
	/Users/mark/go/pkg/mod/github.com/philandstuff/dhall-golang@v1.0.0-rc.2/unmarshal.go:38 +0x1f2
```

**Comment by philandstuff** [comment]
Yes, this isn't implemented.  At some point I will get to this (or someone can submit a PR) but I don't plan on doing this before a 1.0 release which is my current focus.

**Comment by mikroskeem** [comment]
Thank you!

**Comment by mikroskeem** [comment]
Honestly when I requested this feature, I didn't really specify what I really wanted to do with pointer types and that backfires right now :smile:

The idea of pointer type in unmarshaling context is to allow nil values (absent parts of configuration in my case)

After merging #17 I am able to in fact use pointer types, but when a part of configuration is not set, I'll run into `Don't know how to decode <nil> into struct` error.

This works fine for example TOML, or even Go's own JSON implementation.

**Comment by philandstuff** [comment]
Can you open a new issue with this use case please? 🙃

**Comment by mikroskeem** [comment]
Sure thing!
